[#install-on-disconnected-networks]
= Install on disconnected networks

You might need to install {product-title} on {ocp} clusters that are not connected to the Internet, or upgrade an existing
installation to the latest release in such an environment. The procedure to install or upgrade on a disconnected hub
requires some special steps to be performed in addition to the usual install or upgrade flow for a 
connected-network environment.

The notable special steps (details provided below) are:

*	You must have a local image registry that is a mirror of the Openshift operator catalog containing the operator
packages needed for installing or upgrading the Hub and the container images used by those packages.  (You probably 
already set up a local image registry when performing the installation of the {ocp-short} cluster.)
 
*	When creating the `MulticlusterHub` resource that manages the Hub components, you will need to add an additional 
annotation that specifies the name of the catalog source you create for your mirrored catalog.

Before you get started, review the xref:../install/requirements.adoc#requirements-and-recommendations[Requirements and recommendations] section, then see the following documentation:

* <<disconnect-prerequisites,Prerequisites>>
* <<confirm-ocp-installation-2,Confirm your {ocp-short} installation>>
* <<disconnect-configure-olm,Configure Operator Lifecycle Manager>> 
* <<disconnect-configure-icsp,Configure image content source policies>>
* <<disconnect-install-op-and-hub,Install the {product-title} operator and Hub>>

If you are upgrading an existing Hub rather than instlalling a new one, in particular upgrading
from {product-title} release 2.4, please see the following documentation for important new
reuqirements to consider before starting the upgrade:

* <<disconnect-upgrading-from-24, Considerations when upgrading from release 2.4>>

[#disconnect-prerequisites]
== Prerequisites 

You must meet the following requirements before you install {product-title}:

* {ocp} version 4.8 or later must be deployed in your environment, and you must be logged in with the command line 
interface (CLI). 
+
See the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/index[{ocp-short} version 4.10 install documentation] for infomration on installing {ocp}.

* Your {ocp} CLI must be version 4.8 or later, and configured to run `oc` commands.
See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the CLI]
for information about installing and configuring the Red Hat OpenShift CLI.

* Your {ocp} permissions must allow you to create a namespace. Installation fails without a namespace.

* Since you are installing in a disconnected network enviornment, you need access to a local image registry to hold
mirrored OLM catalogs and operator images.  You probably already set up a local image registry when installing the
{ocp-short} cluster in this enviornment, so you should be able to use the same local image registry.

* You must have a workstation that has access to both the Internet as well as your local mirror registry 
 so you can miccor the {ocp} OLM operator catalog and operator images needed for installation or upgrade.

[#confirm-ocp-installation-2]
== Confirm your {ocp-short} installation

* You must have a supported {ocp-short} version, including the registry and storage services, installed and working in your cluster. For information about {ocp-short} version 4.10, see the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/[{ocp-short} Documentation].

* When and if you are connected, run the `kubectl -n openshift-console get route` command to access the {ocp-short} web console. See the following example output:

----
openshift-console          console             console-openshift-console.apps.new-coral.purple-chesterfield.com                       console              https   reencrypt/Redirect     None
----

The console URL in this example is: `https:// console-openshift-console.apps.new-coral.purple-chesterfield.com`. Open the URL in your browser and check the result.

If the console URL displays `console-openshift-console.router.default.svc.cluster.local`,
set the value for `openshift_master_default_subdomain` when you install {ocp-short}.

See xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster] to learn about setting up capacity
for your hub cluster.

== Confirm availability of a local image registry

Installing {product-title} in a disconnected environment involves the use of a local mirror image registry.
Because you have already completed the installation of the {ocp-short} cluster in your disconnected
you will have already set up a mirror registry for use during the {ocp} cluster installation.
For simplicity, we recommend that you use your existing mirror registry for the OLM operator related content.

If you do not already have a local image registry, create one by completing the procedure 
described in topic
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/disconnected-installation-mirroring#mirroring-images-disconnected-install[Mirroring images for a disconnected installation] of the {ocp} documentation.

[#disconnect-configure-olm]
== Configure Operator Lifecycle Manager

Because {product-title} is packaged as an operator, installing, or upgrading it is done using 
Operator Lifecycle Manager (OLM).

In disconnected environments, OLM cannot access the standard operator sources that provide Red Hat provided
operators because they are hosted on image registries that are not accessible from a disconnected cluster.
Instead, a cluster administrator can enable the installation and upgrade of operators on a disconnected environment
using mirrored image registries/operator catalogs.

To prepare your disconnected cluster for installing {product-title}, follow the procedure described in the topic
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/operators/index#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks]
in the {ocp-short} documentation.

When performing those pocedures, please keep in mind the the follow requirements specific
to {product-title}.

[#disconnect-include-acm-pkgs]
=== Include operator packages required for ACM in your mirror catalog

Red Hat provides the {product-title} operator in the Red Hat operators catalog, which is delivered by the
`registry.redhat.io/redhat/redhat-operator-index` index image.
When you prepare your mirror of this catalog index image, you can choose to either mirror the entire catalog as
provided by Red Hat, or you can mirror a subset that contains only the operator packages that you intend to use.

If you are creating a full mirror catalog, no special considerations are needed as all of the packages required
for installing {product-title} will be included.

However, if you are creating a partial/filtered mirrored catalog for which you identify particular packages to be 
included, be sure to include the following package names in your list:

*	`advanced-cluster-manager`
*	`multicluster-engine`

If you are creating the mirrored catalog/registry using the OPM utility (`opm index prune`), include these package
names in the value of the `-p` option as shown in this example:

....
opm index prune \
   -f registry.redhat.io/redhat/redhat-operator-index:v4.10 \
   -p advanced-cluster-management,multicluster-engine \
   -t myregistry.example.com:5000/mirror/my-operator-index:v4.10
....

If yinstead ou are populating the mirrored catalog/registry using the oc-mirror plugin, include these
package names in the packages list portion of your `ImageSetConfiguration`, as shown in this example:

[source,yaml]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
     imageURL: myregistry.example.com:5000/mirror/oc-mirror-metadata
mirror:
  platform:
    channels:
    - name: stable-4.10
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
    packages:
    - name: advanced-cluster-management
    - name: multicluster-engine
  additionalImages: []
  helm: {}
----  

=== Configure OLM to use your mirror registry

When you have populated a local mirror registry with the packages required for installing {product-title},
complete the other steps described in the topic 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/operators/index#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks]
to make your mirror registry and catalog available on your disconnected cluster.
These steps include:

*	https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/operators/index#olm-restricted-networks-operatorhub_olm-restricted-networks[Disabling the default OperatorHub sources]
*	https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/operators/index#olm-mirror-catalog_olm-restricted-networks[Mirroring the Operator catalog]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/operators/index#olm-creating-catalog-from-index_olm-restricted-networks[Adding a catalog source for your mirrored catalog]

=== Take note of the catalog source name

As described in the procedures in the {ocp} documentation, you will add a catalog source to your 
disconnected cluster by adding a `CatalougSource` resource into the `openshift-marketplace` namespace
using a YAML file similar to the following example:

[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-mirror-catalog-source
  namespace: openshift-marketplace
spec:
  image: myregistry.example.com:5000/mirror/my-operator-index:v4.10
  sourceType: grpc
----  

Take note of the name of this resource (the `metadata.name` field) as you will need to specify that same name in 
an annotation of the `MulticlusterHub` resource you will create later.

=== Verify required packages are available

Operator Lifecycle Manager will poll catalog sources for available packages on a regular (timed) interval.
After it has had a chance to poll the catalog source for your mirrored, catalog, you can verify that the
needed packages are available from on your disconnected cluster by querying the available 
`PackageManifest` resources.
You can do so using the following command, directed at your disconnected cluster:
....
oc -n openshift-marketplace get packagemanifests 
....

The list that is displayed should include entries showing the following packages as being supplied by 
the catalog source for your mirror catalog:

*	`advanced-cluster-manager`
*	`multicluster-engine`

[#disconnect-configure-icsp]
== Configure image content source policies 

In order to have your cluster obtain container images for the {product-title} operator from your 
mirror registry (rather than from the internet-hosted registries) you must configure an 
`ImageContentSourcePolciy` on your disconnected cluster to redirected image references to your
mirror registry.  

If you mirrored your catalog using `oc adm catalog mirror` command, the needed image content source 
policy configuration will be in the `imageContentSourcePolicy.yaml` file inside of the `manifests-*`
directory created by that command.  
If, instead, you used the oc-mirror plugin to mirror your catalog, the `imageContentSourcePolicy.yam` 
lfile will instead be within the `oc-mirror-workspace/results-*` directory create by the oc-mirror plugin.

In either case, you can apply the policies to your disconnected command using an `oc apply` or `oc replace`
command such as:
....
oc replace -f ./<path>/imageContentSourcePolicy.yaml
....

The required image content source policy statements can vary based on how you created your mirror registry,
but will be similar to this example:

[source,yaml]
----
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - myregistry.example.com:5000/rhacm2
    source: registry.redhat.io/rhacm2
  - mirrors:
    - myregistry.example.com:5000/multicluster-engine
    source: registry.redhat.io/multicluster-engine
  - mirrors:
    - myregistry.example.com:5000/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - myregistry.example.com:5000/redhat
    source: registry.redhat.io/redhat
----

[#disconnect-install-op-and-hub]
== Install the RHACM operator and Hub

After you have configured OLM and {ocp} as described in earlier sections, you can install {product-title}
using either the OperatorHub UI or a CLI, following the same flow as is described in topic
 xref:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online].

However, there is a special consideration to note when creating the instance of the `MulticlusterHub` resource
that triggeers the installation of your hub.

Because operator installation on a cluster requires the use of a non-default catalog source for the
mirror catalog, a special annotation is needed in the `MulticlusterHub` resource in order to provide the
name of the mirror catalog source to the operator.  The following example shows the required 
`mce-subscrioption-spec` annotation:

[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
   namespace: open-cluster-management
   name: hub
   annotations:
      installer.open-cluster-management.io/mce-subscription-spec: '{"source": "my-mirror-catalog-source"}'
spec: {}
----

If you are creating the resource via CLI, include the `mce-subscription-spec` annotation 
in the YAML you will use with the `oc apply` command to create the `MulticlusterHub` resource.

If you are creating the resource using the OPeratorHub UI, switch to
the YAML view and insert the annotation as shown above.
Note that it is not possible to specify the annotation when usin the field view panels for
creating the `MulticlusterHub`.

[#disconnect-upgrading-from-24]
== Considerations when upgrading from release 2.4

{product-title} release 2.5.0 is the first release in which ACM uses the related multicluster engine for Kubernetes 
operator functionality to provide foundational services that previously were delivered as part of ACM itself.
Releases 2.5 and later of the {product-title} operator will automatically install and manage the required
multicluster engine for Kubernetes operator and `MulticlusterEngine` resource instance as part of its 
installation and upgrade of the Hub.

In connected network environments, it is able to do so without any special actions on the part of the
cluster administrator installing or upgrading RH ACM.

However, because installation of any OLM operator in a disconnected environment involves the use of special mirror
catalogs and catalog sources (as described in the earlier sections), some additional steps are necessary above
what was done when installing ACM release 2.4 or earlier, as described below.

=== Update your procedures for populating the mirror catalog

If, when installing ACM release 2.4, you mirroring procedures created a full copy of the Red Hat operators catalog,
no special updates to your mirroring proecreus are required other than refreshing your catalog to pick up the
updated content for the new operator releases.

If, on the other hand, your procedures populated mirror catalog that is a filtered catalog, you will need to update
your mirroring procedures to ensure that the `multcluster-engine` operator package is included in the 
mirror catalog in addition to the `advanced-cluster-management` package.
Topic <<disconnect-include-acm-pkgs,Include operator packages required for ACM>> 
above above  provides examples of the options to use when populting the mirror catalog.
Update the operator-package lists used in your procedures to match these new requirements.

=== Update your MutliclusterHub resource instance

As described in the topic 
<<disconnect-install-op-and-hub,Install the RHACM operator and Hub>>
above, a new annotation is required on the `MulticlusterHub` resource
when the Hub is being installd or upgraded in a disconnected environment.

For the smoothest upgrade experience, Red Hat recommends that you update your `MulticlusterHub` resource instance
to include the needed annotation before you change the OLM update channel in your OLM subscription
to the `advanced-cluster-management` operator package to trigger the upgrade from release 2.4.
Making this update first allows the upgrade to proceed without delay once initiated.

Use the `oc edit` command to update your `Multiclusterub` resource to add the `mce-subscription-spec` annotation
as shown in this example:

[source,yaml]
----
metadata:
   annotations:
      installer.open-cluster-management.io/mce-subscription-spec: '{"source": "<my-mirror-catalog-source>"}'
----

Replace <my-mirror-catalog-source> shown in this example with the name of the `CatalogSource` resource
(in the `openshift-marketplace` namespace) for your mirror catalog.

If you trigger an upgrade from release 2.4 to release 2.5 before mating this upgrade, the upgrade will begin
but then stall at the point the operator attempts to install a subscription to `multicluster-engine` under the covers.
The status of the `MulitclusterHub` resource will continue to show status `Upgrading` when this occurs.
However, this situation can be corrected, and the upgrade completed by using `oc edit` to add the
`mce-subscription-spec` annocation as shown above.
